[package]
name = "grsrpc"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
bincode = "1.3.3"
futures-channel = "0.3.30"
futures-core = "0.3.30"
futures-util = { version = "0.3.30", features = ["channel"] }
serde = { version = "1.0.193", features = ["derive"] }
